# Generated by Django 2.1.1 on 2018-10-06 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heritagesites', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'managed': False, 'ordering': ['planet', 'region', 'subregion', 'intermediate_region'], 'verbose_name': 'UNSD M49 Location Hierarchy', 'verbose_name_plural': 'UNSD M49 Location Hierarchies'},
        ),
    ]
